# Generated by Django 3.2.7 on 2021-11-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToMeet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persone', models.CharField(max_length=30)),
                ('phone_number', models.IntegerField(max_length=13)),
                ('date_of_meeting', models.DateTimeField(auto_now_add=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('is_favorite', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=20)),
                ('company_name', models.CharField(max_length=30)),
            ],
        ),
    ]
