# Generated by Django 3.2.7 on 2021-11-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0002_tomeet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tomeet',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
